name: Build & Release LuCI App

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build LuCI Package
        id: build
        uses: stevenjoezhang/build-luci-app@v0
        with:
          package: luci-app-adguardhome
          sdk-url:  https://downloads.openwrt.org/releases/24.10.7/targets/x86/64/openwrt-sdk-24.10.7-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          snapsdk-url: https://downloads.openwrt.org/snapshots/targets/armsr/armv8/openwrt-sdk-armsr-armv8_gcc-14.3.0_musl.Linux-x86_64.tar.zst

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
          name: Release v${{ steps.build.outputs.version }}
          tag_name: ${{ github.ref_name }}
